# Generated by Django 3.0.5 on 2020-04-14 21:43

import digifarming.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ArrivalsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartureView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DeparturesView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', digifarming.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=100, unique=True)),
                ('client_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_status', models.IntegerField(default=1)),
                ('client_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100)),
                ('commodity_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_category_name', models.CharField(max_length=100)),
                ('commodity_category_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity_category_status', models.IntegerField(default=1)),
                ('commodity_category_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_metric_name', models.CharField(max_length=100)),
                ('commodity_metric_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity_metric_status', models.IntegerField(default=1)),
                ('commodity_metric_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type_name', models.CharField(max_length=100)),
                ('commodity_type_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity_type_status', models.IntegerField(default=1)),
                ('commodity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityCategory')),
                ('commodity_type_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=50)),
                ('facility_location', models.CharField(max_length=50)),
                ('facility_capacity', models.IntegerField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobShift',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('job_shift', models.CharField(max_length=100)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_shift_status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title_status', models.IntegerField(default=1)),
                ('job_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_order_status', models.IntegerField(default=0)),
                ('order_paid', models.BooleanField(default=False)),
                ('order_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_category_name', models.CharField(max_length=100)),
                ('transport_category_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('transport_category_status', models.IntegerField(default=1)),
                ('transport_category_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackingMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tracking_status', models.CharField(max_length=100)),
                ('user_tracking_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_tracking_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type_name', models.CharField(max_length=100)),
                ('transport_type_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('transport_type_status', models.IntegerField(default=1)),
                ('transport_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityCategory')),
                ('transport_type_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=100)),
                ('transport_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('transport_status', models.IntegerField(default=1)),
                ('transport_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.TransportCategory')),
                ('transport_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.TransportType')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_quantity', models.IntegerField()),
                ('supply_cost', models.IntegerField()),
                ('supply_destination', models.CharField(max_length=100)),
                ('supply_latitude', models.CharField(max_length=100)),
                ('supply_longitude', models.CharField(max_length=100)),
                ('supply_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('supply_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Client')),
                ('supply_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Commodity')),
                ('supply_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supply_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityMetric')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=100)),
                ('is_hr', models.BooleanField(default=False)),
                ('staff_end_date', models.DateTimeField(blank=True, null=True)),
                ('staff_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff_job_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.JobShift')),
                ('staff_job_tUsersitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.JobTitle')),
                ('staff_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type_name', models.CharField(max_length=50)),
                ('request_type_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_type_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.RequestType')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rating_comment', models.TextField(blank=True)),
                ('rating_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Commodity')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityType')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_cost', models.IntegerField()),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='media/meal/')),
                ('meal_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('meal_status', models.IntegerField(default=1)),
                ('meal_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_quantity', models.IntegerField()),
                ('dispatch_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatch_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Commodity')),
                ('dispatch_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher', to=settings.AUTH_USER_MODEL)),
                ('dispatch_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Facility')),
                ('dispatch_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityMetric')),
                ('dispatch_to_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('facility_type_name', models.CharField(max_length=100)),
                ('facility_type_status', models.IntegerField(default=1)),
                ('facility_type_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility_type_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.FacilityType'),
        ),
        migrations.CreateModel(
            name='CustomerTranportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_quantity', models.IntegerField()),
                ('customer_cost', models.IntegerField()),
                ('customer_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Client')),
                ('customer_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Commodity')),
                ('customer_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityMetric')),
                ('customer_transport_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.TransportItems')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityCategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.CommodityType'),
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_name', models.CharField(max_length=100)),
                ('client_type_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_type_status', models.IntegerField(default=1)),
                ('client_type_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.ClientType'),
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cleaning_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.Facility')),
                ('cleaning_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message', models.CharField(max_length=700, null=True)),
                ('chat_type', models.CharField(max_length=100)),
                ('chat_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver', to=settings.AUTH_USER_MODEL)),
                ('chat_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type_name', models.CharField(max_length=100)),
                ('alert_type_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.TextField()),
                ('alert_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digifarming.AlertType')),
            ],
        ),
    ]
