# Generated by Django 3.0.5 on 2020-06-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digifarming', '0003_auto_20200520_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobshift',
            name='shift_end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobshift',
            name='shift_start_time',
            field=models.CharField(max_length=100),
        ),
    ]
