# Generated by Django 3.0.5 on 2020-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digifarming', '0004_auto_20200607_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobshift',
            name='shift_end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobshift',
            name='shift_start_time',
            field=models.CharField(max_length=50),
        ),
    ]
